### ISSUE TITLE
Future of this Idea

### ISSUE THREAD

**Issue by mhsdesign** [sitegeist/Sitegeist.Slipstream#8]
currently this package works by parsing the html and building it together which is a small performance factor.

can this idea not faster be solved by having some global mutable context variable (or php with static var) which consists of the content for the header? (would then need to be more explicit declared than just having an attribute name in the html)

we would apply that as process to the whole page and string_replace the contents into a marked (stringidentified) position (marked by this package in neos.page.head fusion)

**Comment by jonnitto** [comment]
Do you mean something like `@slipstream` and then push it to the given location?
This way, we would lose the feature that the component could be put in any location, not only `head` or `body`.

**Comment by mhsdesign** [comment]
yes similar something like this: you can define anywhere a slipstream position ... but i get it, before you didnt need to actually define a position ...

like:
```
root = Neos.Neos:Page {
    head = Sitegeitst.Slipstream:Position {
        ankhor = 'head'
    }
}

prototype(YourVendor:FusionPrototype) < prototype(Neos.Fusion:Component) {

    renderer = afx`
        <Sitegeitst.Slipstream:Teleport position='head'>
            <script>...
        </Sitegeitst.Slipstream:Teleport>

        .... foo . bar
    `
}
```

**Comment by mficzel** [comment]
@mhsdesign i would like to see a smarter solution but have a hard time figuring out how this would look together with fusion caching.

**Comment by mficzel** [comment]
@mhsdesign how about simply checking "str_contains($responseBody, "data-slipstream") before firing up the xpath logic and do a fast return in case it is not found. That would avoid unneeded dom reading and searching.  

Other than that "some custom markers" sounds more dirty to me than the current solution.
